### ISSUE TITLE
http://goooogle.com/

### ISSUE THREAD

**Issue by EpickyHrac** [sk-cat/fluffy-blocklist#1]
random trash with sscam
![image](https://user-images.githubusercontent.com/66244226/101348538-12fbc980-388c-11eb-97bc-9141ac210361.png)

**Comment by slovak-cat** [comment]
niesi jediny

**Comment by EpickyHrac** [comment]
> niesi jediny

ik

**Comment by slovak-cat** [comment]
![PjONypc](https://user-images.githubusercontent.com/50016870/101348747-771e8d80-388c-11eb-8d27-f9b62030e35d.png)
